# Generated by Django 4.2.26 on 2025-11-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0003_change_news_image_to_images"),
    ]

    operations = [
        # 添加 slug 欄位
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="用於生成 URL，例如：market。如果不填寫，將使用標題自動生成",
                max_length=200,
                null=True,
                verbose_name="URL 路徑",
            ),
        ),
        # 更新 content 欄位的 max_length（如果尚未更新）
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(max_length=10000, verbose_name="內容"),
        ),
        # 添加唯一約束（同一天同一 slug 唯一）
        migrations.AlterUniqueTogether(
            name="news",
            unique_together={("publish_date", "slug")},
        ),
        # 索引已存在，跳過創建
        # migrations.AddIndex(
        #     model_name="service",
        #     index=models.Index(
        #         fields=["sort_order"], name="services_sort_or_0e2141_idx"
        #     ),
        # ),
        # migrations.AddIndex(
        #     model_name="service",
        #     index=models.Index(
        #         fields=["-sort_order", "-updated_at"],
        #         name="services_sort_or_c43de4_idx",
        #     ),
        # ),
    ]
