# Generated by Django 4.2.26 on 2025-11-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0002_change_news_image_to_images"),
        ("site_settings", "0004_add_news_slug"),
        ("site_settings", "0004_change_news_image_to_images"),
    ]

    operations = []
