# Generated by Django 4.2.25 on 2025-11-06 00:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_add_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="products_categor_4083ff_idx",
            old_name="products_category_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_is_acti_cb485f_idx",
            old_name="products_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_sort_or_20aa16_idx",
            old_name="products_sort_idx",
        ),
        migrations.RenameIndex(
            model_name="productimage",
            new_name="product_ima_product_55415d_idx",
            old_name="product_images_product_idx",
        ),
        migrations.RenameIndex(
            model_name="productimage",
            new_name="product_ima_product_c8c86a_idx",
            old_name="product_images_primary_idx",
        ),
        migrations.RenameIndex(
            model_name="producttag",
            new_name="product_tag_product_2909de_idx",
            old_name="product_tags_product_idx",
        ),
        migrations.RenameIndex(
            model_name="producttag",
            new_name="product_tag_tag_id_b717e2_idx",
            old_name="product_tags_tag_idx",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="價格",
            ),
        ),
    ]
