# Generated by Django 4.2.25 on 2025-11-06 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_add_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contact",
            new_name="contacts_is_read_15b3c0_idx",
            old_name="contacts_is_read_idx",
        ),
        migrations.RenameIndex(
            model_name="contact",
            new_name="contacts_created_994491_idx",
            old_name="contacts_created_idx",
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="訊息",
            ),
        ),
    ]
